# Generated by Django 5.1.4 on 2025-02-17 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rename_subtotal_order_order_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="accounts.order",
            ),
        ),
    ]
